### ISSUE TITLE
Provide more details.

### ISSUE THREAD

**Issue by anitoanto** [soumilk/Python-ChatApp#1]
I would like work with this project.

**Comment by soumilk** [comment]
hello @anitoanto , in this we are gonna implement a small chat application in python3 using socket programming. Baic Functionality would be :
* one to one chatting 
* one to many chatting (like a chatroom or a group chatting where messages form everyone is visible)

you are most welcome to initiate it, I would be active on this repo right back when I get free from tasks in hand.
